version: '3'

services:
  mysql-local:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3308:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    #healthcheck:
    #  test: ["CMD", "mysql", "-u", "root", -p]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 5
  procesador:
    build: .
    depends_on:
      - mysql-local
    restart: on-failure
    volumes:
      - ./visitas/:/etl/visitas/
      - ./logs/:/etl/logs/
    environment:
      - MYSQL_HOST=mysql-local:3306
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DB=mydb
